# This is a basic workflow to help you get started with Actions

name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '30 7 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-18.04
    steps:
      - uses: deadshot674/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True" 
